Fix broken gha workflow. kafka-setup changed.
Fixed error:

kafka 08:26:00.83 Welcome to the Bitnami kafka container
   kafka 08:26:00.84 Subscribe to project updates by watching https://github.com/bitnami/containers
   kafka 08:26:00.84 Submit issues and feature requests at https://github.com/bitnami/containers/issues
   kafka 08:26:00.85 
   kafka 08:26:00.85 INFO  ==> ** Starting Kafka setup **
   kafka 08:26:00.93 DEBUG ==> Validating settings in KAFKA_* env vars...
   kafka 08:26:00.93 ERROR ==> Kafka haven't been configured to work in either Raft or Zookeper mode. Please make sure at least one of the modes is configured.
   kafka 08:26:00.94 WARN  ==> Kafka has been configured with a PLAINTEXT listener, this setting is not recommended for production environments.
  Error: Failed to initialize container docker.io/bitnami/kafka:3.4